# This Github workflow will run tests on any push to main or pull request open.

name: test
on:
  push:
    branches:
      - main
    paths:
      - src/
  pull_request:
    paths:
      - src/
  workflow_dispatch:

jobs:
  test:
    name: cargo-test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux]
        include:
          - build: linux
            os: ubuntu-latest
            rust: stable
            target: x86_64-unknown-linux-musl
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}

      - name: Cache Build Artifacts
        uses: Swatinem/rust-cache@v2.7.3

      - name: Run Tests
        run: cargo test --target ${{ matrix.target }}
